apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deluge-config-pvc
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path 
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deluge
  namespace: apps
  labels:
    app: deluge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deluge
  strategy:
    type: Recreate 
  template:
    metadata:
      labels:
        app: deluge
    spec:
      containers:
        - name: deluge
          image: binhex/arch-delugevpn:2.2.0-1-04
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          ports:
            - containerPort: 8112
              name: web
            - containerPort: 58846
              name: daemon
            - containerPort: 58946
              name: bt-tcp
            - containerPort: 58946
              protocol: UDP
              name: bt-udp
            - containerPort: 8118
              name: httpproxy
          env:
            - name: VPN_ENABLED
              value: "yes"
            - name: VPN_PROV
              value: "custom"
            - name: ENABLE_PRIVOXY
              value: "yes"
            - name: STRICT_PORT_FORWARD
              value: "yes"
            - name: LAN_NETWORK
              value: "10.42.0.0/16,10.43.0.0/16"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/New_York"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: deluge-config-pvc
        - name: media
          persistentVolumeClaim:
            claimName: nfs-media-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: deluge-svc
  namespace: apps
spec:
  type: LoadBalancer
  selector:
    app: deluge
  ports:
    - name: web
      protocol: TCP
      port: 8112
      targetPort: 8112
    - name: daemon
      protocol: TCP
      port: 58846
      targetPort: 58846
    - name: bittorrent-tcp
      protocol: TCP
      port: 58946
      targetPort: 58946
    - name: bittorrent-udp
      protocol: UDP
      port: 58946
      targetPort: 58946
    - name: httpproxy
      protocol: TCP
      port: 8118
      targetPort: 8118
