apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr-config-pvc
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path 
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: readarr
  namespace: apps
  labels:
    app: readarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readarr
  strategy:
    type: Recreate 
  template:
    metadata:
      labels:
        app: readarr
    spec:
      containers:
        - name: readarr
          image: lscr.io/linuxserver/readarr:nightly
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/New_York"
          ports:
            - containerPort: 8787
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /data
            - name: media
              mountPath: /media
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: readarr-config-pvc
        - name: media
          persistentVolumeClaim:
            claimName: nfs-media-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: readarr-svc
  namespace: apps
spec:
  type: LoadBalancer
  selector:
    app: readarr
  ports:
    - protocol: TCP
      port: 8787
      targetPort: 8787
